sudo: required
dist: trusty

language: c

# send build/failure notifications only to a specific
# email address and only on a status change
notifications:
  email:
    recipients:
      - svn@yam.ch
    on_success: change
    on_failure: change

# download and install our required cross compilers
install:
  # Make sure we can install i386 packages as some adtools binaries
  # requires i386 libraries being installed to work in the 64bit env
  # of Travis
  - sudo dpkg --add-architecture i386
  - sudo apt-get -qq update || true
  - sudo apt-get -qq install libc6:i386
  # Install all adtools related stuff we need
  - if [[ ! ${BUILD} =~ unix|mingw32 ]]; then curl -L https://dl.bintray.com/jens-maus/adtools/adtools-utils.tar.bz2 | sudo tar xj -C / ; fi
  - if [[ ${BUILD} =~ os3|release ]]; then curl -L https://dl.bintray.com/jens-maus/adtools/adtools-m68k-amigaos.tar.bz2 | sudo tar xj -C / ; fi
  - if [[ ${BUILD} =~ os4|release ]]; then curl -L https://dl.bintray.com/jens-maus/adtools/adtools-ppc-amigaos.tar.bz2 | sudo tar xj -C / ; fi
  - if [[ ${BUILD} =~ mos|release ]]; then curl -L https://dl.bintray.com/jens-maus/adtools/adtools-ppc-morphos.tar.bz2 | sudo tar xj -C / ; fi
  - if [[ ${BUILD} =~ aros-ppc|release ]]; then curl -L https://dl.bintray.com/jens-maus/adtools/adtools-ppc-aros.tar.bz2 | sudo tar xj -C / ; fi
  - if [[ ${BUILD} =~ aros-i386|release ]]; then curl -L https://dl.bintray.com/jens-maus/adtools/adtools-i386-aros.tar.bz2 | sudo tar xj -C / ; fi
  - if [[ ${BUILD} =~ aros-x86_64|release ]]; then curl -L https://dl.bintray.com/jens-maus/adtools/adtools-x86_64-aros.tar.bz2 | sudo tar xj -C / ; fi
  - if [[ ${BUILD} =~ mingw32|release ]]; then sudo apt-get -qq install binutils-mingw-w64-i686 gcc-mingw-w64-i686 ; fi

# set the PATH variable to the directories the cross compilers are installed.
before_script:
  - export PATH=/usr/local/amiga/bin:/opt/m68k-amigaos/bin:/opt/ppc-amigaos/bin:/opt/ppc-morphos/bin:${PATH}

# specify a list of variables to test (here we test the build for our supported
# list of operating systems).
env:
  - BUILD="OS=unix"
  - BUILD="OS=unix DEBUG="
  - BUILD="OS=os4"
  - BUILD="OS=os4 DEBUG="
  - BUILD="OS=os3"
  - BUILD="OS=os3 DEBUG="
  - BUILD="OS=mos"
  - BUILD="OS=mos DEBUG="
  - BUILD="OS=aros-ppc"
  - BUILD="OS=aros-ppc DEBUG="
  - BUILD="OS=aros-i386"
  - BUILD="OS=aros-i386 DEBUG="
  - BUILD="OS=aros-x86_64"
  - BUILD="OS=aros-x86_64 DEBUG="
  - BUILD="OS=mingw32"
  - BUILD="OS=mingw32 DEBUG="
  - BUILD="release"

# the build command to execute for each test
script:
  - make -j1 ${BUILD}
